owner: laymoth
repo: status

sites:
  - name: Website
    url: https://laymoth.dev
  - name: Ali's Git
    url: https://xdeveryti.me/
  - name: Redirect - GitHub
    url: https://gh.laymoth.dev
  - name: Redirect - Matrix
    url: https://matrix.laymoth.dev

assignees:
  - laymoth

status-website:
  baseUrl: /status
  themeUrl: https://cdn.statically.io/gh/laymoth/status/master/assets/custom.css
  name: Laymoth Status
  navbar:
    - title: ~/
      href: /
      
commitMessages:
  summaryJson: ":shipit: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: ":trollface: Update graphs [skip ci]"
  commitAuthorName: "Ali"
  commitAuthorEmail: "49151035+alirhmnxd@users.noreply.github.com"
