owner: laymoth
repo: status

sites:
  - name: Website
    url: https://laymoth.dev
  - name: Moepository
    url: https://pkgs.moezee.space
  - name: Moezee
    url: https://moezee.space
  - name: Bio
    url: https://xdeveryti.me

assignees:
  - laymoth

status-website:
  favicon: https://github.com/laymoth.png
  theme: dark
  cname: status.laymoth.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Laymoth Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO