owner: laymoth
repo: status

sites:
  - name: Website
    url: https://laymoth.dev
  - name: Redirect - Git
    url: https://gh.laymoth.dev
  - name: Redirect - Twitter
    url: https://tw.laymoth.dev
    method: POST
  - name: Redirect - Matrix
    url: https://matrix.laymoth.dev
    method: POST

assignees:
  - laymoth

status-website:
  baseUrl: /status
  themeUrl: https://cdn.statically.io/gh/laymoth/status/master/assets/custom.css
  logoUrl: https://github.com/alirhmnxd.png
  name: Laymoth Status
  navbar:
    - title: Home
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      
commitMessages:
  summaryJson: ":card_file_box: Update status summary [skip ci]"
  statusChange: "$EMOJI $SITE_NAME is $STATUS ($RESPONSE_CODE in $RESPONSE_TIME ms) [skip ci]"
  graphsUpdate: ":trollface: Update graphs [skip ci]"
  commitAuthorName: "Ali"
  commitAuthorEmail: "49151035+alirhmnxd@users.noreply.github.com"
