owner: laymoth
repo: status

sites:
  - name: Website
    url: https://laymoth.dev
  - name: Moepository
    url: https://pkgs.moezee.space
  - name: Moezee
    url: https://moezee.space
  - name: Bio
    url: https://xdeveryti.me/laymoth

assignees:
  - laymoth

status-website:
  baseUrl: /status
  theme: light
  logoUrl: https://github.com/laymoth.png
  name: Laymoth Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
